/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-11 15:07:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<title>JSP AJAX</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	var searchRequest = new XMLHttpRequest();\r\n");
      out.write("	var registerRequest = new XMLHttpRequest();\r\n");
      out.write("	function searchFunction()\r\n");
      out.write("	{\r\n");
      out.write("		searchRequest.open(\"Post\", \"./UserSearchServlet?userName=\" + encodeURIComponent(document.getElementById(\"userName\").value), true);\r\n");
      out.write("		searchRequest.onreadystatechange = searchProcess;\r\n");
      out.write("		searchRequest.send(null);\r\n");
      out.write("	}\r\n");
      out.write("	function searchProcess()\r\n");
      out.write("	{\r\n");
      out.write("		var table = document.getElementById(\"ajaxTable\");\r\n");
      out.write("		table.innerHTML = \"\";\r\n");
      out.write("		\r\n");
      out.write("		// 성공적인 통신인지 확인\r\n");
      out.write("		if(searchRequest.readyState == 4 && searchRequest.status == 200) {\r\n");
      out.write("			var object = eval('(' + searchRequest.responseText + ')');\r\n");
      out.write("			var result = object.result;\r\n");
      out.write("			for(var i=0; i<result.length; i++) \r\n");
      out.write("			{\r\n");
      out.write("				var row = table.insertRow(0);\r\n");
      out.write("				\r\n");
      out.write("				// 셀을 탐색\r\n");
      out.write("				for(var j=0; j<result[i].length; j++)\r\n");
      out.write("				{\r\n");
      out.write("					var cell = row.insertCell(j);\r\n");
      out.write("					cell.innerHTML = result[i][j].value;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	function registerFunction()\r\n");
      out.write("	{\r\n");
      out.write("		registerRequest.open(\"Post\", \"./UserRegisterServlet?userName=\" + encodeURIComponent(document.getElementById(\"registerName\").value) +\r\n");
      out.write("									\"&userAge=\" + encodeURIComponent(document.getElementById(\"registerAge\").value) + \r\n");
      out.write("									\"&userGender=\" + encodeURIComponent($('input[name=registerGender]:checked').val()) + \r\n");
      out.write("									\"&userEmail=\" + encodeURIComponent(document.getElementById(\"registerEmail\").value) , true);\r\n");
      out.write("		registerRequest.onreadystatechange = registerProcess;\r\n");
      out.write("		registerRequest.send(null);\r\n");
      out.write("	}\r\n");
      out.write("	function registerProcess()\r\n");
      out.write("	{\r\n");
      out.write("		if(registerRequest.readyState == 4 && registerRequest.status == 200){\r\n");
      out.write("			var result = registerRequest.responseText;\r\n");
      out.write("			\r\n");
      out.write("			if(result != 1) {\r\n");
      out.write("				alert('등록에 실패했습니다.');\r\n");
      out.write("			}\r\n");
      out.write("			else {\r\n");
      out.write("				// 성공하면 공백으로 바꾸기\r\n");
      out.write("				var userName = document.getElementById(\"userName\");\r\n");
      out.write("				var registerName = document.getElementById(\"registerName\");\r\n");
      out.write("				var registerAge = document.getElementById(\"registerAge\");\r\n");
      out.write("				var registerEmail = document.getElementById(\"registerEmail\");\r\n");
      out.write("				userName.value = \"\";\r\n");
      out.write("				registerName.value = \"\";\r\n");
      out.write("				registerAge.value = \"\";\r\n");
      out.write("				registerEmail.value = \"\";\r\n");
      out.write("				\r\n");
      out.write("				//회원 출력하기\r\n");
      out.write("				searchFunction();\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	window.onload = function ()\r\n");
      out.write("	{\r\n");
      out.write("		searchFunction();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<br />\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"form-group row pull-right\">\r\n");
      out.write("			<div class=\"col-xs-8\">\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"userName\" onkeyup=\"searchFunction();\" size=\"20\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-xs-2\">\r\n");
      out.write("				<button class=\"btn btn-primary\" onclick=\"searchFunction();\" type=\"button\">검색</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<table class=\"table\" style=\"text-align: center; border: 1px solid #dddddd\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th style=\"background-color: #fafafa; text-align: center;\">이름</th>\r\n");
      out.write("					<th style=\"background-color: #fafafa; text-align: center;\">나이</th>\r\n");
      out.write("					<th style=\"background-color: #fafafa; text-align: center;\">성별</th>\r\n");
      out.write("					<th style=\"background-color: #fafafa; text-align: center;\">이메일</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody id=\"ajaxTable\">\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<table class=\"table\" style=\"text-align: center; border: 1px solid #dddddd;\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th colspan=\"2\" style=\"background-color: #fafafa; text-align: center;\">\r\n");
      out.write("					회원 등록 양식\r\n");
      out.write("					</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"background-color: #fafafa; text-align: center;\">\r\n");
      out.write("						<h5>이름</h5>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" id=\"registerName\" size=\"20\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"background-color: #fafafa; text-align: center;\">\r\n");
      out.write("						<h5>나이</h5>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" id=\"registerAge\" size=\"20\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"background-color: #fafafa; text-align: center;\">\r\n");
      out.write("						<h5>성별</h5>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"form-group\" style=\"text-align: center; margin: 0 auto;\">\r\n");
      out.write("							<div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("								<label class=\"btn btn-primary active\">\r\n");
      out.write("									<input type=\"radio\" name=\"registerGender\" autocomplete=\"off\" value=\"남자\" checked=\"checked\" />남자\r\n");
      out.write("								</label>\r\n");
      out.write("								<label class=\"btn btn-primary\">\r\n");
      out.write("									<input type=\"radio\" name=\"registerGender\" autocomplete=\"off\" value=\"여자\"/>여자\r\n");
      out.write("								</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"background-color: #fafafa; text-align: center;\">\r\n");
      out.write("						<h5>이메일</h5>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" id=\"registerEmail\" size=\"20\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\">\r\n");
      out.write("						<button class=\"btn btn-primary pull-right\" onclick=\"registerFunction();\" type=\"button\">등록</button>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
